[tool.towncrier]
package = "treq"
package_dir = "src"
filename = "docs/changes.rst"
directory = "newsfragments"
title_format = "{version} ({project_date})"
issue_format = "`#{issue} <https://github.com/twisted/treq/issues/{issue}>`__"
